language: java
install: mvn install
jdk:
  - oraclejdk6
  - oraclejdk7
  - openjdk6
notifications:
  email: 
    recipients:
      - travis-ci@mortardata.com
    on_success: change
    on_failure: always
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "B5t84zHDbb8hUZ8mwPj4udJERnLO++F/V/NM9JhTJ+vl74UU3lMh3NpIUz/i\n83eiE5gvRU+LxIJ/brC4LNr6gqoOwa4D/64zXSYKPD65f7QD5mp33AvfRVMY\nsmRLcL9l4iNCncFGLs6zANbd3o3SK9zugbGt93sCfhsI5pg3Wtg="
